name: 'Set Deployment Status'
description: 'Set the status of a Github Deployment'
author: 'Peachjar Engineering'
inputs:
  token:
    required: true
    description: Github token used to create the deployment.
  deploymentId:
    required: true
    description: ID of the deployment to set the status of.
  repository:
    required: false
    description: The github repository (owner/repo) that is being deployed
    default: ${{ github.repository }}
  state:
    required: true
    description: State of the deployment (one of the valid Github DeploymentStatus.state values
    default: ''
  description:
    required: false
    description: 'An optional description about the deployment status change'
  channelId:
    required: false
    description: 'An optional slack channel-id to notify if the deploy status is "failure"\'
  slackToken:
    required: false
    description: 'Slack webhook URL to send messages when deploy fail'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '12.x'

    - name: Run script 
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_DEPLOYMENTID: ${{ inputs.deploymentId }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_STATE: ${{ inputs.state}}
        INPUT_DESCRIPTION: ${{ inputs.description }}
      run: |
        cd ${{github.action_path}}
        node dist/index.js

    - name: Send slack message on failure
      id: slack
      if: ${{ inputs.state == 'failure' && inputs.channelId != '' }}
      uses: slackapi/slack-github-action@v1.25.0
      with:
        channel-id: '${{ inputs.channelId }}'
        payload: |
          {
            "text": "Deployment for ${{ github.repository }} - failed",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":alert: *Deployment for ${{ github.repository }} - failed* :fire_engine:\n Check github workflow for more information"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":github: Failed action"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slackToken }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
