name: 'Set Deployment Status'
description: 'Set the status of a Github Deployment'
author: 'Peachjar Engineering'
inputs:
  token:
    required: true
    description: Github token used to create the deployment.
  deploymentId:
    required: true
    description: ID of the deployment to set the status of.
  repository:
    required: false
    description: The github repository (owner/repo) that is being deployed
    default: ${{ github.repository }}
  state:
    required: true
    description: State of the deployment (one of the valid Github DeploymentStatus.state values
    default: ''
  description:
    required: false
    description: 'An optional description about the deployment status change'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '12.x'

    - name: Run script 
      shell: bash
      env:
        token: ${{ inputs.token }}
        deploymentId: ${{ inputs.deploymentId }}
        repository: ${{ inputs.repository }}
        state: ${{ inputs.state}}
        description: ${{ inputs.description }}
      run: |
        node dist/index.js
