name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - 'master'
      - 'dependabot/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '12.x'  
    - uses: actions/checkout@v4
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: deploy
      uses: peachjar/action-trigger-deployment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: staging
        description: Test deployment
        requiredContexts: ''
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        deploymentId: ${{ steps.deploy.outputs.deployment_id }}
        state: in_progress
        description: Deployment is in progress
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        deploymentId: ${{ steps.deploy.outputs.deployment_id }}
        state: success
        description: Deployment was successful
